obj-$(CONFIG_PCI_ALTERA_EUTECUS) += eutecus-pci.o

eutecus-pci-y :=    eutecus-altera-pci.o            \
                    eutecus-devicefile.o            \
                    eutecus-altera-v4l2.o           \
                    eutecus-altera-v4l2-ioctl.o     \
                    eutecus-altera-interrupt.o      \
                    eutecus-videobuf2.o

